### ISSUE TITLE
Same compilation environment for both platforms

### ISSUE THREAD

**Issue by auraoupa** [nextsimdg/nextsimdg#103]
In our continuous integration workflow we are compiling the code and running tests on ubuntu and macos platforms. To get the needed librairies (boost, catch2, cmake and netcdf) we used apt-get for ubuntu and brew for macos, resulting in different version for some libraries. Now that for instance catch2 has moved to version 3 that we don't want to use yet,  we need to be more specific when defining our environment. Therefore I propose we do it with conda for both platforms

**Comment by timspainNERSC** [comment]
The fact that we have successfully been running the CI for more than a year suggests that this is not a real problem. With only two OSes, using the native (or in the case of homebrew near-native) package manager for each platformseems to be less trouble than introducing conda in to the system. I, for one, am more comfortable fixing problems in homebrew and apt than in conda.

Closing for now.
