### ISSUE TITLE
ModelArrayRef should provide access to Eigen::Matrix data

### ISSUE THREAD

**Issue by timspainNERSC** [nextsimdg/nextsimdg#111]
ModelArrayRef is built around ModelArray and its Eigen::Array base. The data stored in the dynamics is contained in Eigen::Matrix variables. If the access to these was entirely transparent, then the dynamics data could be easily shared into the physics code. The trick is to do this with a minimum of interference to the existing dynamics code and classes.

**Comment by timspainNERSC** [comment]
Since ModelArrayRef is just wrapper around accessing the `ModelArray* ModelComponent::sharedArrays` and `const ModelArray* ModelComponent::protectedArrays`, the stored pointers to ModelArray instances should allow access to a class that holds a Eigen::Matrix, rather than a Eigen::Array. This could potentially be achieved by a derived class, though that does introduce virtual functions where they are not necessarily welcome.

However, the other place where ModelArray is used is as part of ModelState. This directly contains copies of the ModelArray data, and so to work in the same fashion, there needs to be only one ModelArray class with no derived classes and no templating.

**Comment by timspainNERSC** [comment]
Possible solutions

1. Copy data in to and out from the dynamics arrays at the start and end of the dynamics part.
   - Could be very slow.
2. Build ModelArray around the common Eigen base class of both Array and Matrix and make sure the right operations occur on the right interpretation of the data
3. Build ModelArray around Eigen::Matrix. Provide transparent pass-throughs for the Matrix operations
   - These two options rely on the Magdeburg group being willing to use the Nextsim::ModelArray class rather than the underlying Eigen::Matrix class.
4. Change ModelArray to be a typedef of Eigen::Matrix, and rework everything else around that concept
   - Provide some helper functions/classes to do everything that the current ModelArray class does

**Comment by einola** [comment]
Please refer to PR number and close issue.

**Comment by timspainNERSC** [comment]
Merged as part of PR #101 
Closed.
