### ISSUE TITLE
Configuration dataflow

### ISSUE THREAD

**Issue by timspainNERSC** [nextsimdg/nextsimdg#113]
Currently, the configuration for the model is

1. Stored as defaults
2. Stored in the config files, the names of which are passed as command line arguments
3. Read from command line arguments as ultimate overrides

This works fine as the model currently stands, but needs to be more sophisticated as the model gets more complex and users begin to need to save, restore and inspect the settings of a given model run.

Some command line help information wouldn't go amiss either.

**Comment by timspainNERSC** [comment]
I have included Anton as someone who has had something to say on such matters in the past.

**Comment by einola** [comment]
The current status you describe above is the same as we have for Lagrangian neXtSIM, and I think it works well.

In addition, we also write out a log into the output directory which contains all options and the git revision used. This has been indispensable for me, personally, when trying to figure out what changes what. So, I would say such a log, plus simply copying the config file to the output directory (as we also do now) should be sufficient for the user to be able to go back and see what options etc. were used in a run. I agree that putting this into the output files is overkill.

We now also want the config options to be put into the restart file, which I think is a good idea. In that case, we have the following priority for options:

 1. Defaults in the code
 2. Overridden by options read in from restart file
 3. Overridden by options read in from config file
 4. Overridden by options read in as command-line options

How does that sound? I guess the log should contain a list of overrides, in an easily parseable way. Not sure what that would look like yet.

As for keeping track of changes to options and defaults, then it gets a bit hairy. Changing defaults, option names, etc, is an interface change which will lead to unexpected changes in results if you're not paying attention. So, if we do that we should bump the major version of the whole model ... which is not feasible. Not sure what's best here(!)

**Comment by einola** [comment]
A thought on versioning - which is becoming a bit removed, but ok: We could have a versioning of w.x.y.z, where

w: Major physics changes like new rheology or thermodynamics or discretisation is now the default
x: Interface changes (new default options for configs, basically)
y: New features, but they're not the default
z: Bug fixes

The difference between w and x is largely subjective, but I think it may be needed anyway.

**Comment by timspainNERSC** [comment]
I don't think we have to or should stick rigidly to Semantic Versioning and [its rules](https://semver.org/#semantic-versioning-specification-semver). Especially since the first rule is
> 1. Software using Semantic Versioning MUST declare a public API.

We certainly don't do that. So we could change config defaults without changing the major version number, if that's what we say we are doing. And keep documenting changes in comprehensive changelogs.

My suggestion is a year.build (or year.release) version system.

**Comment by timspainNERSC** [comment]
Two things that are required from the configuration that are not currently possible:

1. A list of all current configuration options in a running model, to be output at metadata to the restart file.
2. Help text and options for all possible module implementations, their configuration options and sub-modules, to be available as help text on the command line.

If the help text used in point 2 can be used to generate offline documentation, then all the better.

This means that the configurations passed in on the command line and in the configuration files needs to be cached in some structure which has knowledge of the current or total available configuration.

But without it all being written in one big ol' file.

**Comment by timspainNERSC** [comment]
Test of the configuration option help markdown output:
> # CCSMIceAlbedo
> 
> ## CCSMIceAlbedo.iceAlbedo
> _numeric_    range: 0—1  (default = 0.538000)
> Albedo of snow-free ice.
> 
> ## CCSMIceAlbedo.snowAlbedo
> _numeric_    range: 0—1  (default = 0.825600)
> Albedo of snow.
> 
> 
> # FiniteElementFluxes
> 
> ## nextsim_thermo.drag_ocean_q
> _numeric_    range: 0—∞ ?? (default = 0.001500)
> Coefficient for evaporative mass flux calculation.
> 
> ## nextsim_thermo.drag_ocean_t
> _numeric_    range: 0—∞ ?? (default = 0.000830)
> Coefficient for sensible heat flux calculation.
> 
> ## nextsim_thermo.drag_ice_t
> _numeric_    range: 0—∞ ?? (default = 0.001300)
> Ice drag coefficient for heat fluxes.
> 
> ## nextsim_thermo.albedoW
> _numeric_    range: 0—∞  (default = 0.070000)
> Shortwave albedo of open ocean water.
> 
> ## nextsim_thermo.I_0
> _numeric_    range: 0—∞  (default = 0.170000)
> Transmissivity of ice.
> 
> 
> # HiblerSpread
> 
> ## Hibler.h0
> _numeric_    range: 0—∞ m (default = 0.250000)
> The thickness of newly frozen ice.
> 
> ## Hibler.phiM
> _numeric_    range: 0—∞  (default = 0.500000)
> Power-law exponent for melting ice.
> 
> 
> # IceGrowth
> 
> ## nextsim_thermo.min_conc
> _numeric_    range: 0—1  (default = 0.000000)
> Minimum allowed ice concentration.
> 
> ## nextsim_thermo.min_thick
> _numeric_    range: 0—∞ m (default = 0.010000)
> Minimum allowed ice thickness.
> 
> 
> # MissingData
> 
> ## model.missing_value
> _numeric_    range: -∞—∞  (default = -2³⁰⁰)
> Missing data indicator used for input and output.
> 
> 
> # Model
> 
> ## model.start
> _string_
> Model start time, formatted as an ISO8601 date. Non-calendretical runs can start from year 0 or 1. 
> 
> ## model.stop
> _string_
> Model stop time, formatted as an ISO8601 data.  Will be overridden if a model run length is set. 
> 
> ## model.run_length
> _string_
> Model run length, formatted as an ISO8601 duration (P prefix). Overrides the stop time if set. 
> 
> ## model.time_step
> _string_
> Model physics timestep, formatted a ISO8601 duration (P prefix). 
> 
> ## model.init_file
> _string_
> The file path to the restart file to use for the run.
> 
> 
> # Modules
> 
> ## Modules.Nextsim::IVerticalIceGrowth
> _module_ [**Nextsim::ThermoIce0**]
> The module which calculates the one-dimensional ice thermodynamics.
> 
> ## Modules.Nextsim::ILateralIceSpread
> _module_ [**Nextsim::HiblerSpread**]
> The module for calculating the freezing and thawing of ice on the ocean surface.
> 
> ## Modules.Nextsim::IFluxCalculation
> _module_ [**Nextsim::FiniteElementFluxCalc**]
> The module for calculating surface-atmosphere exchange fluxes.
> 
> ## Modules.Nextsim::IIceAlbedo
> _module_ [**Nextsim::SMUIceAlbedo**, Nextsim::SMU2IceAlbedo, Nextsim::CCSMIceAlbedo]
> The module for calculating the albedo of the ice surface.
> 
> ## Modules.Nextsim::IIceOceanHeatFlux
> _module_ [**Nextsim::BasicIceOceanHeatFlux**]
> The module for calculating the ice-ocean heat fluxes.
> 
> ## Modules.Nextsim::IDiagnosticOutput
> _module_ [**Nextsim::SimpleOutput**]
> The module controlling the output of NetCDF files containing diagnostic model data.
> 
> ## Modules.Nextsim::AtmosphereState
> _module_ [**Nextsim::DummyAtmosphereState**]
> The module selecting how the state of the atmosphere is obtained.
> 
> ## Modules.Nextsim::OceanState
> _module_ [**Nextsim::DummyOceanState**]
> The module selecting how the state of the ocean is obtained.
> 
> 
> # ThermoIce0
> 
> ## thermoice0.ks
> _numeric_    range: 0—∞ W K⁻¹ m⁻¹ (default = 0.309600)
> Thermal conductivity of snow.
>
