### ISSUE TITLE
Revised version numbering

### ISSUE THREAD

**Issue by einola** [nextsimdg/nextsimdg#121]
A thought on versioning: We could have a versioning of w.x.y.z, where

w: Major physics changes like new rheology or thermodynamics or discretisation is now the default
x: Interface changes (new default options for configs, basically)
y: New features, but they're not the default
z: Bug fixes

The difference between w and x is largely subjective, but I think it may be needed anyway.

_Originally posted by @einola in https://github.com/nextsimdg/nextsimdg/issues/113#issuecomment-1168468201_

**Comment by einola** [comment]
@timspainNERSC replied to this with:

I don't think we have to or should stick rigidly to Semantic Versioning and [its rules](https://semver.org/#semantic-versioning-specification-semver). Especially since the first rule is
> 1. Software using Semantic Versioning MUST declare a public API.

We certainly don't do that. So we could change config defaults without changing the major version number, if that's what we say we are doing. And keep documenting changes in comprehensive changelogs.

My suggestion is a year.build (or year.release) version system.

_Originally posted by @timspainNERSC in https://github.com/nextsimdg/nextsimdg/issues/113#issuecomment-1209537780_

**Comment by einola** [comment]
It's a good point that we don't do a public API. We only have a human interface, which is the config files, and I feel we need to warn the users in a quite clear way if we change those.

So, while my suggestion maybe has too many numbers I'm inclined to think that a year.build versioning doesn't give enough information.

Any other suggestions?

**Comment by timspainNERSC** [comment]
If two are not enough, and four too many, then sure three is the correct number of numbers:
year.release.patch

For example: 2022.1.3

I'd suggest we encourage using just year.release as far as we can, with the patch number only being important when discussing bugs, regressions and other development focussed matters. The encouragement being in release notes, web pages and other communication from the development team. But if that's not what ends up getting used, then that's fine too, I guess.

**Comment by auraoupa** [comment]
I do not have strong opinion about numerotation for versioning, I am more used to increasing number of version that shows the improvement in the developing of the code but I am not against a temporal marker such as year at the beginning.

Documenting the change is however the most important thing in my opinion, I've created a page in the documentation for that purpose : https://nextsim-dg.readthedocs.io/en/latest/changelog.html, you can fill it here : https://github.com/nextsimdg/nextsimdg/blob/docs/docs/changelog.rst

**Comment by einola** [comment]
Ok, I think we'll just stick with the three numbers we have now, but they're not exactly semantic versioning then. So for x.y.z we have

 - increment of z when there's a hotfix (bugfix) pushed to main
 - increment of y when develop is merged into main
 - increment of x when we've been working on something extraordinary, when there's a major change in interface (configs or outputs) ... or when y is becoming too big (26 is industry standard I believe).

We need to

 - review the read-me and make sure that this is what it says
 - set up a system where each pull request has a headline and description and that these go into the change log, together with the version number.

**Comment by einola** [comment]
Closed by PR  #136
