### ISSUE TITLE
More complex output: ConfiguredOutput

### ISSUE THREAD

**Issue by timspainNERSC** [nextsimdg/nextsimdg#124]
The current SimpleOutput implementation takes in everything and outputs everything every timestep. A slightly more sophisticated version could at least take a output period for the files to be created.

Additionally, take a list of fields and only output the named fields, rather than everything.

**Comment by einola** [comment]
Would also be nice to put everything in one file with a time dimension.

**Comment by timspainNERSC** [comment]
I was hoping to let XIOS deal with that

**Comment by einola** [comment]
Ok, that's fine. I just thought that if it was very little effort, then it could be done. But we really don't want to spend much time on this issue, so skip that idea.

**Comment by timspainNERSC** [comment]
Y U no close automatically on merge?

**Comment by einola** [comment]
Sorry - forgot o_o
