### ISSUE TITLE
Configured simple atmosphere and ocean state

### ISSUE THREAD

**Issue by einola** [nextsimdg/nextsimdg#129]
At the moment we have "dummy" atmosphere and ocean state modules. The DummyAtmosphereState has a hard-coded atmosphere state and DummyOceanState reads its state from the restart file.

We also need slightly more sophisticated dummy states, where the values are read in from a config file.

**Comment by timspainNERSC** [comment]
How sophisticated do you need? Constant values? Spatially uniform monthly samples? `rand() / a - T0`?

**Comment by einola** [comment]
Let's start with constant values, read in from a config file :)

The most complicated variant I can imagine is someone writing an Atmosphere or OceanState with an analytical forcing that can take in some optional parameters. But in this case the "constant values from options" version can act as a template.
