### ISSUE TITLE
Passing time values to parameterizations

### ISSUE THREAD

**Issue by timspainNERSC** [nextsimdg/nextsimdg#133]
Parameterizations (such as ice albedo) might be time dependent. Currently they have no canonical way of accessing or being passed the current model time.

Fix this.

**Comment by einola** [comment]
Importantly, this is also needed for the ice type (multi-year ice) tracer.

**Comment by timspainNERSC** [comment]
Only two time-dependent modules exist that are not derived classes of ModelComponent (which usually have an `update(const TimestepTime&)` function). These are the ice albedo and the diagnostic output. The latter already gets passed a `ModelMetadata` instance which holds the current time.

So, right now, only the ice albedo possibly needs a special time value. As a result, I will just extend the interface to allow the setting of the current time (as a TimePoint for generality).

**Comment by timspainNERSC** [comment]
> Importantly, this is also needed for the ice type (multi-year ice) tracer.

Since this is a bit of a special tracer, do you want to draw up a specification for it, or shall I have a look at what happens in Old Nextsim?

**Comment by timspainNERSC** [comment]
Closing: merged
