### ISSUE TITLE
Debug preprocessor option

### ISSUE THREAD

**Issue by einola** [nextsimdg/nextsimdg#134]
We should have a CPP key (e.g. DEBUG), that allows us to do sanity checks etc, which should not be run in production.

This includes
 - tailor-made checks inside an ``#ifdef DEBUG`` clause
 - out-of-bounds checks on standard objects like ``ModelArray``
 - an ``assert(bool, string)`` call

**Comment by timspainNERSC** [comment]
[A solution from stackoverflow](https://stackoverflow.com/a/51190178).
The CMake function `add_compile_options("$<$<CONFIG:DEBUG>:-DDEBUG>")` adds a macro definition `DEBUG` if (and only if) the build is defined as a Debug build.
