### ISSUE TITLE
Sea surfaces and slab models

### ISSUE THREAD

**Issue by timspainNERSC** [nextsimdg/nextsimdg#143]
In an email, @einola wrote:

> - When in stand-alone mode SST and SSS are prognostic variables and need to be in the restart file. I was thinking that they should be set by config options, but I was wrong and was thinking the old-neXtSIM-way.
>
> - When coupled to an ocean model SST and SSS are simply received from the ocean model and don’t need to go into the restart file.

And that in Lagrangian nextSIM,
> There are two SST and SSS values floating around, unfortunately (when running in stand-alone mode, that is). The prognostic SST and SSS, which need to be initialised and put in the restart file, and the “forcing” SST and SSS, which are read in from file or set as constants. The forcing SST and SSS are then simply used to nudge the prognostic SST and SSS towards something sensible.

**Comment by timspainNERSC** [comment]
To re-implement the same functionality, we need to
- re-introduce optional SST & SSS fields into the restart file
- create a slab-ocean OceanState implementation
- distinguish between prognostic SST/S and climatological SST/S
- etc?

**Comment by einola** [comment]
I like this suggestion. The SlabOceanState module needs to

 - Read and write from a restart file
 - Be forced by either constants or by data read in from file. I guess this could require further modularisation, but I'm thinking now that's overkill.

Also, the forcing/climatological SST/S should only appear in SlabOceanState.

**Comment by timspainNERSC** [comment]
> - Be forced by either constants or by data read in from file. I guess this could require further modularisation, but I'm thinking now that's overkill.

A perfect use case for in-module configuration, I would say.

**Comment by timspainNERSC** [comment]
When forcing the ocean through climatologies, the values are never directly used, but instead always go through the slab ocean

**Comment by einola** [comment]
Closing this following the merge of #157

NB: More work to be done, following issue #154
