### ISSUE TITLE
Providing working version of BBM

### ISSUE THREAD

**Issue by pminak** [nextsimdg/nextsimdg#156]
BBM gives NaNs on LKF Benchmark. Tuning parameters, eventually modification of tilde P.

**Comment by einola** [comment]
It seems the reason BBM gives NaNs is that damage becomes equal to one, causing ``time_viscous`` to become zero and ``multiplicator`` to become NaN.

The time evolution equations don't allow damage to become equal to one - only to approach it asymptotically. I guess what's happening is that there's a slight overshoot in the advection (as is to be expected) and that this is only capped to ``<= 1`` and not ``< 1``.

For now, I am testing this with a ``.min(1.-1e-12)`` call when creating ``d_gauss``. But I guess this should be controlled in the advection?

See branch issue156_BBM_crash.

**Comment by einola** [comment]
Yes, that's a good point too @ailefroide! We'll have a look.

**Comment by einola** [comment]
Depends on PR #204
