### ISSUE TITLE
Implement simplistic ERA5 and TOPAZ forcing implementations

### ISSUE THREAD

**Issue by timspainNERSC** [nextsimdg/nextsimdg#194]
In order to run models that are reasonably representative of the real world, real-world forcings need to be used.
For a certain grid (Arctic only, fixed resolution) implement forcing ingestion functions that work only with forcing data that has been preprocessed to match the spatial extent and resolution of the model. Time interpolation is still required.

**Comment by timspainNERSC** [comment]
@einola
What kind of grid should we be aiming for?
What kind of time extent?

**Comment by einola** [comment]
We should assume that the data is on the model grid (only mean values - no DG components). Interpolation is done in pre-processing (with e.g., python).

We should also assume that each variable (2m temp, SST, etc) is in a separate netCDF file and that the file covers the entire simulation length (presumably a few months).

The only flexibility I can't see us avoiding easily is that the atmospheric forcing is at an hourly frequency and the ocean at a daily frequency. So, the model would have to be told the frequency at which it needs to read the data - but that can be a module option.

**Comment by timspainNERSC** [comment]
PR merged
