### ISSUE TITLE
``develop`` does not compile with ``-DCMAKE_BUILD_TYPE=Debug``

### ISSUE THREAD

**Issue by einola** [nextsimdg/nextsimdg#245]
The ``develop`` branch does not compile using the debug build type. There seems to be a conflict with the ``DEBUG`` CPP key and the definition of ``DEBUG`` in ``Logged::level``. A simple workaround is to rename one or the other, but there could be a more elegant solution.

Steps to reproduce. In the model root directory, do the following:

```
git checkout develop
mkdir build_error
cd build_error
cmake -DCMAKE_BUILD_TYPE=Debug ..
make
```

Using Apple Clang
```
Monaco:build einola$ c++ --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
the result of ``make`` is
```
Monaco:build einola$ make
[  0%] Building CXX object CMakeFiles/nextsim.dir/core/src/main.cpp.o
In file included from /Users/einola/src/nextsimdg/core/src/main.cpp:13:
In file included from /Users/einola/src/nextsimdg/core/src/include/Model.hpp:10:
/Users/einola/src/nextsimdg/core/src/include/Logged.hpp:23:9: error: expected identifier
        DEBUG,
        ^
<command line>:2:15: note: expanded from here
#define DEBUG 1
              ^
In file included from /Users/einola/src/nextsimdg/core/src/main.cpp:13:
In file included from /Users/einola/src/nextsimdg/core/src/include/Model.hpp:10:
/Users/einola/src/nextsimdg/core/src/include/Logged.hpp:60:73: error: expected unqualified-id
    static void debug(const std::string& message) { log(message, level::DEBUG); };
                                                                        ^
<command line>:2:15: note: expanded from here
#define DEBUG 1
              ^
2 errors generated.
make[2]: *** [CMakeFiles/nextsim.dir/core/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/nextsim.dir/all] Error 2
make: *** [all] Error 2
```

The model compiles fine if I don't use ``-DCMAKE_BUILD_TYPE=Debug``.

**Comment by einola** [comment]
Assigned to @timspainNERSC - but feel free to send it to Cambridge if you like!

**Comment by einola** [comment]
One option is to use ``NDEBUG`` and ``#ifndef NDEBUG`` for debugging sections.

Pro: ``NDEBUG`` is standard nomenclature
Con: ``#ifndef NDEBUG`` is a double negative

**Comment by timspainNERSC** [comment]
The problem is that I defined a `DEBUG` level in the logging. The preprocessor replaces this all-caps debug with the defined constant value one, resulting in the invalid identifier `Level::1`. I need to change the name of that particular logging level (I think).
