### ISSUE TITLE
Errors in Winton and Semtner thermodynamics

### ISSUE THREAD

**Issue by einola** [nextsimdg/nextsimdg#320]
There are errors in the neXtSIM Lagrangian implementation of the Winton (2000) and Semtner (1976) thermodynamics models.

 - In the Winton model, I use "I = I_0*Qsw" without taking into account that I_0 is 0 with (thick enough) snow cover
 - In the Semtner model, I don't apply the gamma fudge factor, and only the beta fudge factor through the albedo scheme - but not the one we usually use.

Both errors stem from improper treatment of the penetration of short-wave radiation into the ice, so a fix to both fits together.

These are being addressed in neXtSIM Lagrangian by adding I (the penetrating short-wave radiation) as an output to IABulkFluxes and using this in the Winton and Semtner models. A similar approach should be taken in neXtSIM_DG.

**Comment by timspainNERSC** [comment]
Fixes implemented and merged.
