### ISSUE TITLE
Make dynamics parameters available as config options

### ISSUE THREAD

**Issue by einola** [nextsimdg/nextsimdg#726]
The dynamics parameters are the defaults of specific classes (DynamicsParameters, MEVPParameters, and MEBParameters if memory serves). These must, however, be configurable by the user through config files.

**Comment by yumengch** [comment]
Hi Einar,

I just see this issue as I'm looking at the ways for parameter perturbations. Will the air and ocean drag coefficient be in the config files?

What is the current plan for the implementation? I can imagine this is not the priority so I may take a chance if necessary. 

I'm also interested in knowing the possiblity to make certain parameters spatially varying, e.g., becoming a vector/matrix in the model. What will be the ideal approach in nextSIM-DG?

Cheers,
Yumeng

**Comment by einola** [comment]
Hi Yumeng,

Yes, the drag coefficients will be in the config file. The development stopped a bit there because I wasn't sure how to do that properly. The drag coefficients are common for all rheologies, so they should be treated slightly differently than the rheology-specific parameters. This is a design question and not a technical problem!

I need to get this out soon for my work, so I plan to finish next week.

The drag coefficients will become spatially varying in the future, but we have yet to plan for this.

**Comment by einola** [comment]
Hi Yumeng,

The drag parameters are now available as a config file option. See here:  #730

You can also run `./nextsim --help-config BBMDynamics` or `./nextsim --help-config MEVPDynamics` for a short help text.

Cheers,

Einar
