### ISSUE TITLE
Self-contained modules

### ISSUE THREAD

**Issue by einola** [nextsimdg/nextsimdg#82]
We should try and have the modules as self-contained as possible. If a model contains a single physical process, then different formulations or parameterisations of that process may have different complexities. This leads to different module implementations for the same process (like albedo calculation) that can have

 - a different number of variables that need to be advected (prognostic variables)
 - a different number of variables that don't need to be advected, but could be interesting to output (diagnostic variables)

Ideally, a module would do the following:

```
Get inputs (probably by reading PrognosticData/ElementData on input)
Do physics and modify prognostic and diagnostic variables
Broadcast diagnostic outputs (to XIOS)
Return modified diagnostic variables (presumably by modifying the input PrognosticData/ElementData)
```

**Comment by timspainNERSC** [comment]
It turns out I needed to read the issue text more carefully. PR #83 is an important step towards solving this, but far from the only component.

**Comment by timspainNERSC** [comment]
ModelModule implements enough of this to close for now, I think.
