### ISSUE TITLE
Setup for clang-format

### ISSUE THREAD

**Issue by einola** [nextsimdg/nextsimdg#9]
We need to have a setup where the formating of clang-format is enforced. I don't know how to best do that. Maybe @auraoupa can find or @pminak knows?

I'll start a new branch and commit the .clang-format file we decided on in there.

**Comment by einola** [comment]
Link to branch: issue9_clang_format

**Comment by einola** [comment]
Branch name: issue9_clang_format

**Comment by pminak** [comment]
Yes, now we should use the file .clang-format with the editor of choice and/or as a pre-commit hook.
Finally, to be sure, we can configure Server-Side Hook as well.

**Comment by timspainNERSC** [comment]
This has been working for ages.
